// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEXAA1OhZtvKpKsswd39oiD1RHMo81JCU',
    appId: '1:717029246915:web:a0266782097b91f72a5f76',
    messagingSenderId: '717029246915',
    projectId: 'propereal-71cf5',
    authDomain: 'propereal-71cf5.firebaseapp.com',
    storageBucket: 'propereal-71cf5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUaUDjCW8fikXZ8FS9pt7a_cyBUrJbMjY',
    appId: '1:717029246915:android:ab0faa123c004bac2a5f76',
    messagingSenderId: '717029246915',
    projectId: 'propereal-71cf5',
    storageBucket: 'propereal-71cf5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb8xmPs7aISal1TWoalAnxWXeOINjCUHE',
    appId: '1:717029246915:ios:047fbf5dc4600bd52a5f76',
    messagingSenderId: '717029246915',
    projectId: 'propereal-71cf5',
    storageBucket: 'propereal-71cf5.appspot.com',
    iosClientId: '717029246915-n5ss2nr0peldhlcbghjivu44q7quo0sd.apps.googleusercontent.com',
    iosBundleId: 'com.example.propereal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCb8xmPs7aISal1TWoalAnxWXeOINjCUHE',
    appId: '1:717029246915:ios:fd1c8b484d676b142a5f76',
    messagingSenderId: '717029246915',
    projectId: 'propereal-71cf5',
    storageBucket: 'propereal-71cf5.appspot.com',
    iosClientId: '717029246915-dgfun4i0q7iie7oopacn10dphk77lc5u.apps.googleusercontent.com',
    iosBundleId: 'com.example.propereal.RunnerTests',
  );
}
